<title>Nooges.com</title>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php echo $this->css($css_nooges, 'screen', false); ?>

<?php echo $this->js($js_jquery); ?>
<?php echo $this->js($js_nooges); ?>

<script type="text/javascript">
	$(document).ready(function() {
		zebraStripe();
		
		$('#response-list-left, #response-list-right').bind('zebra-stripe', function() {
			zebraStripe();
		});
	});
	
	function zebraStripe() {
		$('#response-list-left > li:even, #response-list-right > li:even').attr('class', 'zebra1');
		$('#response-list-left > li:odd, #response-list-right > li:odd').attr('class', 'zebra2');
	}
</script>