<h1>Daily Nooge - <?php echo $nooge->getSubject(); ?></h1>

<p>
	<?php echo Library::parseBbc($nooge->getBody()); ?>
</p>

<div class="nooge">
	<div class="nooge-left">
		<div class="inner">
			<form method="post" action="#" class="reply">
				<label>Agree Here?</label>
				<textarea name="response" rows="3" id="response-left"></textarea>
				<p>
					<input class="button" type="button" value="respond" onclick="Nooges.create('response-list-left', 'response-left', <?php echo $nooge->getIdTopic(); ?>, 0, 0);" />
				</p>
			</form>
		
			<h3>Responses</h3>
			<ul class="zebra-stripe" id="response-list-left">
				<?php echo $this->response_list_left; ?>
			</ul>
		</div>
	</div>
	
	<div class="nooge-right">
		<div class="inner">
			<form method="post" action="#" class="reply">
				<label>Agree Here?</label>
				<textarea name="response" rows="3" id="response-right"></textarea>
				<p>
					<input class="button" type="button" value="respond" onclick="Nooges.create('response-list-right', 'response-right', <?php echo $nooge->getIdTopic(); ?>, 0, 1);" />
				</p>
			</form>
			
			<h3>Responses</h3>
			<ul class="zebra-stripe" id="response-list-right">
				<?php echo $this->response_list_right; ?>
			</ul>
		</div>
	</div>
</div>