<h1>Daily Nooge - <?php echo $nooge->getSubject(); ?></h1>

<p>
	<?php echo Library::parseBbc($nooge->getBody()); ?>
</p>

<div style="text-align: right">
	<a class="addthis_button" href="http://addthis.com/bookmark.php?v=250&amp;username=nooges" addthis:url="<?php echo $site_url; ?>?id=<?php echo $nooge->getIdTopic(); ?>" addthis:title="Nooges.com - Discussion about <?php echo $nooge->getSubject(); ?>">
		<img src="http://s7.addthis.com/static/btn/sm-share-en.gif" width="83" height="16" alt="Bookmark and Share" style="border:0"/>
	</a>
	<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#username=nooges"></script>
</div>

<div class="nooge">
	<div class="nooge-left">
		<div class="inner">
			<form method="post" action="#" class="reply">
				<label>Agree Here?</label>
				<textarea rows="3" id="response-left"></textarea>
				<p>
					<input class="button" type="button" value="respond" onclick="Nooges.create('response-list-left', 'response-left', <?php echo $nooge->getIdTopic(); ?>, 0, 0);">
				</p>
			</form>
		
			<h3>Responses</h3>
			<ul class="response-list" id="response-list-left">
				<?php echo $this->response_list_left; ?>
			</ul>
		</div>
	</div>
	
	<div class="nooge-right">
		<div class="inner">
			<form method="post" action="#" class="reply">
				<label>Agree Here?</label>
				<textarea rows="3" id="response-right"></textarea>
				<p>
					<input class="button" type="button" value="respond" onclick="Nooges.create('response-list-right', 'response-right', <?php echo $nooge->getIdTopic(); ?>, 0, 1);">
				</p>
			</form>
			
			<h3>Responses</h3>
			<ul class="response-list" id="response-list-right">
				<?php echo $this->response_list_right; ?>
			</ul>
		</div>
	</div>
</div>