<div id="header">			
	<span id="slogan">Talk Trash Daily</span>
	
	<ul>
		<li id="current"><a href="/"><span>Home</span></a></li>
		<li><a href="/forum/index.php?action=register"><span>Register</span></a></li>
		<li><a href="/forum/index.php?action=login"><span>Login</span></a></li>
		<li><a href="/forum/index.php"><span>Discussion Forums</span></a></li>
	</ul>
</div>

<div id="header-logo">			
	<div id="logo">nooges<span class="red">.com</span></div>
	<form method="post" class="search" action="/forum/index.php?action=search2">
		<p>
			<input name="search" class="textbox" type="text" />
			<input name="search" class="searchbutton" value="Search" type="submit" />
		</p>
	</form>
</div>