<?php echo $response_list_html; ?>

<?php if ( false === $is_parent ): ?>
	<li class="last" id="response-form-<?php echo $parent_id; ?>">
		<form method="post" action="#" class="respond">
			<textarea rows="2" id="response-left-<?php echo $parent_id; ?>"></textarea>
			<p><input class="button" type="button" value="respond" onclick="Nooges.create('response-list-children-<?php echo $parent_id; ?>', 'response-left-<?php echo $parent_id; ?>', <?php echo $topic_id; ?>, <?php echo $parent_id; ?>, <?php echo $side; ?>);"></p>
		</form>
	</li>
<?php endif; ?>