<div id="sidebar" >							
	<h1>Discussion Forums</h1>
	<div class="left-box">
		<ul class="sidemenu">
			<?php $i = 1; ?>
			<?php $length = $board_list->length(); ?>
			<?php foreach ( $board_list as $board ): ?>
				<li <?php echo ( $i++ == $length ? 'class="last"' : NULL ); ?>>
					<a href="/forum/index.php?board=<?php echo $board->id(); ?>">
						<?php echo $board->getName(); ?>
					</a>
				</li>
			<?php endforeach; ?>
		</ul>
	</div>
</div>