<!doctype html>
<head>
	<?php echo $this->getBlock('header'); ?>
</head>

<body>
	<div id="wrap">
		<?php echo $this->getBlock('menu'); ?>
		<?php echo $this->getBlock('sidebar'); ?>

		<div id="main">
			<?php echo $this->getBlock('body'); ?>
		</div>
		
		<?php echo $this->getBlock('footer'); ?>
	</div>
	
	<input type="hidden" name="token" id="token" value="<?php echo Nooges::getToken(); ?>">
</body>
</html>