<?php if ( false === defined('NOOGES') ) exit; ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<title>Nooges.com</title>

	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />

	<link rel="stylesheet" href="css/nooges.css" type="text/css" />
	
	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript">
		var Nooges = {
			respond: function(response_id, side, parent_id) {
				var message = $('#' + response_id).val();
				if ( 0 == message.length ) {
					alert('Please enter a response first!');
				}
				
				var data = {
					action: 'respond',
					message: message,
					side: side,
					parent_id: parent_id
				};
				
				this.postHtml('respond.http.php', data, function(html) {


				});
			},

			
			loadResponseList: function() {
				
			},
			
			
			
			like: function(response_id) {
				response_id = parseInt(response_id);
				if ( true == isNaN(response_id) || response_id < 1 ) {
					alert('Please select a proper response first!');
				}
				
				var data = {
					action: 'like',
					response_id: response_id
				};
				
				this.postHtml('respond.http.php', data, function(html) {
					$('#response-likes-' + response_id).html('').html(html);
				});
			},
			
			dislike: function(response_id) {
				response_id = parseInt(response_id);
				if ( true == isNaN(response_id) || response_id < 1 ) {
					alert('Please select a proper response first!');
				}
				
				var data = {
					action: 'dislike',
					response_id: response_id
				};
				
				this.postHtml('respond.http.php', data, function(html) {
					$('#response-dislikes-' + response_id).html('').html(html);
				});
			},
			
			openResponse: function(response_id, side) {
				$('#response-' + response_id).after('<li class="response last"><form method="post" action="#" class="respond"><textarea rows="3" id="nooges-response-' + response_id + '"></textarea><p><input class="button" type="button" value="Respond" onclick="Nooges.respond(\'nooges-response-' + response_id + '\', ' + side + ', ' + response_id + ');" /></p></form></li>');
				$('#response-link-' + response_id).hide();
			},
			
			postHtml: function(url, data, callback) {
				$.post(url, data, callback, 'html');
			},
			
			postJson: function(url, data, callback) {
				$.post(url, data, callback, 'json');
			},
			
			getToken: function() {
				return $('#token').val();
			},
			
			buildUrl: function(url, form_id) {
				var qs = $('#' + form_id).serialize();
				url += '?' + qs;
				return url;
			}
		}
	</script>
</head>

<body>

	<div id="wrap">

		<div id="header">			
			<span id="slogan">Talk Trash Daily</span>
			
			<ul>
				<li id="current"><a href="/index.php"><span>Home</span></a></li>
				<li><a href="/forum/index.php?action=register"><span>Register</span></a></li>
				<li><a href="/forum/index.php?action=login"><span>Login</span></a></li>
				<li><a href="/forum/index.php"><span>Discussion Forums</span></a></li>
			</ul>
		</div>

		<div id="header-logo">			

		<div id="logo">nooges<span class="red">.com</span></div>
		<form method="post" class="search" action="/forum/index.php?action=search2">
			<p>
				<input name="search" class="textbox" type="text" />
				<input name="search" class="searchbutton" value="Search" type="submit" />
			</p>
			</form>
		</div>
		
		<div id="sidebar" >							
			<h1>Discussion Forums</h1>
			<div class="left-box">
				<ul class="sidemenu">
					<?php foreach ( $board_list as $board ): ?>
						<li>
							<a href="/forum/index.php?board=<?php echo $board['id_board']; ?>.0">
								<?php echo $board['name']; ?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>

			<h1>Daily Poll</h1>
			<div class="left-box">
				Daily Poll in here
			</div>

			<h1>Comment Of The Day</h1>
			<div class="left-box">
				<p>
					<em>The Saint's will suck my sweaty nutsack.</em>
				</p>
			</div>
		</div>		

		<div id="main">				
			<h1>Daily Nooge - <?php echo $nooge['subject']; ?></h1>

			<p>
				<?php echo nooges_bbc_parse($nooge['body']); ?>
			</p>  

			<div class="nooge">
				<div class="nooge-left">
					<div class="inner">
						<form method="post" action="#" class="reply" id="respond-left">
							<label>Respond!</label>
							<textarea name="response" rows="3" id="response-left-0"></textarea>
							<p>
								<input class="button" type="button" value="Respond" onclick="Nooges.respond('response-left-0', 0, 0)" />
							</p>
						</form>
					
						<h3>Responses</h3>
						<ul>
							<?php $i = 0; ?>
							<?php foreach ( $response_list_left as $response ): ?>
								<?php $nrid = $response['nooges_response_id']; ?>
								<li id="response-<?php echo $nrid; ?>" class="<?php echo $zebra_list[$i++%2]; ?>">
									<?php echo nl2br(nooges_remove_html($response['body'])); ?>
									<div class="author">- <?php echo $response['poster_name']; ?></div>
									<div class="action-list">
										<a href="javascript:Nooges.openResponse(<?php echo $nrid; ?>, 0)" id="response-link-<?php echo $nrid; ?>">respond</a>
										<a href="javascript:Nooges.like(<?php echo $nrid; ?>)">
											+like (<span id="response-likes-<?php echo $nrid; ?>"><?php echo $response['likes']; ?></span>)
										</a>
										<a href="javascript:Nooges.dislike(<?php echo $nrid; ?>)">
											-dislike (<span id="response-dislikes-<?php echo $nrid; ?>"><?php echo $response['dislikes']; ?></span>)
										</a>
										<a href="#">see responses</a>
									</div>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
				
				<div class="nooge-right">
					<div class="inner">
						<form method="post" action="#" class="reply" id="respond-right">
							<label>Respond!</label>
							<textarea name="response" rows="3" id="response-right"></textarea>
							<p>
								<input class="button" type="button" value="Respond" onclick="Nooges.respond('response-right', 1, 0)" />
							</p>
						</form>
						
						<h3>Responses</h3>
						<ul>
							<?php $i = 0; ?>
							<?php foreach ( $response_list_right as $response ): ?>
								<li class="<?php echo $zebra_list[$i++%2]; ?>">
									<?php echo nl2br(nooges_remove_html($response['body'])); ?>
									<div class="author">- <?php echo $response['poster_name']; ?></div>
									<div class="action-list">
										<a href="#">respond</a>
										<a href="#">+ like</a>
										<a href="#">- dislike</a>
										<a href="#">see responses</a>
									</div>
								</li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="footer">
		<p>	
			&copy; 2010 <strong>Nooges.com</strong> &nbsp;&nbsp;
			Design by: <a href="http://www.styleshout.com/">styleshout</a> | 
			<a href="index.html">Home</a> | <a href="index.html">Site Map</a> | <a href="index.html">RSS Feed</a>
		</p>
	</div>

</body>
</html>